# Generated by Django 4.2.26 on 2025-11-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
