# Generated by Django 4.2.26 on 2025-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_supplier_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone__isnull", False)),
                fields=("phone",),
                name="unique_phone_when_not_null",
            ),
        ),
    ]
