# Generated by Django 4.2.26 on 2025-12-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_customer_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="accessories",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="opening_side",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="remarks",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_item_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
