# Generated by Django 4.2.26 on 2025-12-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_product_accessories_product_opening_side_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.supplier"
            ),
        ),
    ]
