# Generated by Django 4.2.26 on 2025-12-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_product_supplier_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("main_door", "Main Door"),
                    ("secondary_door", "Secondary Door"),
                    ("accessory", "Accessory"),
                    ("material", "Raw Material"),
                    ("service", "Service/Labour"),
                    ("others", "Others"),
                ],
                max_length=20,
            ),
        ),
    ]
